= Personal Records Manager

This project is a proof of concept for managing personal data for a group of persons.

These code samples are designed to be used together with http://www.apress.com/9781484208090[*Pivotal Certified Spring Web Application Developer Exam*] study guide.
Detailed instructions on how to use them can be found in the book.
Please buy the book, it will mean a lot to me. Also, feedback is welcome!

== Building and Deploying
This is a Gradle multi-module project. The *-practice projects, have tests and pieces left unimplemented so building the full project using:
----
gradle build
----
will fail.

In order to build the full project and skipping tests, build from the root  (`parent-records`) directory:
----
gradle build -x test 
----

.Later updates(19.01.2016)
* all modules with names too long to fit in a 256 limited windows path were renamed - the Webflows specific modules. Just in case, 
if you use Windows use a really short path for your workspace ( ex: C:\workspace)
* Switched to Spring version 4.2.4.RELEASE
* Switched to Spring Data JPA 1.9.2.RELEASE
* Switched to Spring Security 4.0.3.RELEASE
* Switched to Spring Boot 1.3.1.RELEASE
* Switched to Hibernate 5.0.7.Final
* Switched to *.adoc format for the README file